version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run: 
          name: 'install dependences'
          command: npm install -f
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: 'run test'
          command: npm test
      - coveralls/upload
workflows:
  trojans-ec-fe-workflow:
    jobs: 
      - build
